repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Standard lint
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

      # Specific file format linters
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks

      # Security linters
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
